# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772d0c94d0fa2e7dea5031f2faaa1589816d2507aaa324fe6b77444ba887a319827b3a1ce03e01359faaa4e7a893f61fd9552bcb12b0c2471d4457b00b553237

  stripe_publishable_key: pk_test_lmtp4C8D3gyonQ9nMbpSlQxE
  stripe_secret_key:      sk_test_RQvD3kf1Gg8HcptwQmskXEuX

test:
  secret_key_base: 53596a201460da531c16e5443c31871cf2a2c05ff9fbff11104c03a26d112369f42e8f5a641f0e7cac6da2622975ea19e3d2f126e276c519be40c2d30194c667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
